print("Equal to operator")
print(1 == 1)
print(1 == 0)
print("Not Equal operator")
print(1 != 1)
print(1 != 0)
print("Greater than")
print(1 > 0)
print(0 > 1)
print("less than")
print(1 < 0)
print(0 < 1)
print("Greater or Equal")
print(1 >= 1)
print(1 >= 2)
print("Less or Equal")
print(1 <= 1)
print(0 <= -1)